# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "29fa276b3481ffe7496b77e628a3ca5c"
name = "Csv_parser"
application_url = "https://escape-buddy-compliant-latex.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory,read_locations"

[auth]
redirect_urls = [ "https://escape-buddy-compliant-latex.trycloudflare.com/api/auth" ]
